"""rename address

Revision ID: 1bb737ad5ce6
Revises: 9875d6611ada
Create Date: 2024-10-02 19:56:39.385581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb737ad5ce6'
down_revision = '9875d6611ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name="location")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name="address")
    # ### end Alembic commands ###
